parameters:
    sfynx.trigger.entities.listener.class: Sfynx\TriggerBundle\EventListener\EntitiesContainer

    sfynx.trigger.listener.onclear.class: Sfynx\TriggerBundle\EventListener\OnClearListener
    sfynx.trigger.listener.postload.class: Sfynx\TriggerBundle\EventListener\PostLoadListener
    sfynx.trigger.listener.loadclassmetadata.class: Sfynx\TriggerBundle\EventListener\loadClassMetadataListener
    sfynx.trigger.listener.preflush.class: Sfynx\TriggerBundle\EventListener\PreFlushListener
    sfynx.trigger.listener.onflush.class: Sfynx\TriggerBundle\EventListener\OnFlushListener
    sfynx.trigger.listener.postflush.class: Sfynx\TriggerBundle\EventListener\PostFlushListener
    sfynx.trigger.listener.preremove.class: Sfynx\TriggerBundle\EventListener\PreRemoveListener
    sfynx.trigger.listener.postremove.class: Sfynx\TriggerBundle\EventListener\PostRemoveListener
    sfynx.trigger.listener.prepersist.class: Sfynx\TriggerBundle\EventListener\PrePersistListener
    sfynx.trigger.listener.postpersist.class: Sfynx\TriggerBundle\EventListener\PostPersistListener
    sfynx.trigger.listener.preupdate.class: Sfynx\TriggerBundle\EventListener\PreUpdateListener
    sfynx.trigger.listener.postupdate.class: Sfynx\TriggerBundle\EventListener\PostUpdateListener
    sfynx.trigger.listener.schema.class: Sfynx\TriggerBundle\EventListener\SchemaListener

services:
    #
    # configuration of the persist Entities container
    #
    sfynx.trigger.entities.listener:
        class: '%sfynx.trigger.entities.listener.class%'
        public: true
        arguments: ['@service_container']

    #
    # Doctrine events Configuration
    #
    sfynx.trigger.onclear_listener:
        class: '%sfynx.trigger.listener.onclear.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: onClear, connexion: default }

    sfynx.trigger.schema_listener:
        class: '%sfynx.trigger.listener.schema.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema, connexion: default }

    sfynx.trigger.postload_listener:
        class: '%sfynx.trigger.listener.postload.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad, connexion: default }

    sfynx.trigger.loadclassmetadata_listener:
        class: '%sfynx.trigger.listener.loadclassmetadata.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connexion: default }

    sfynx.trigger.preflush_listener:
        class: '%sfynx.trigger.listener.preflush.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: preFlush, connexion: default }

    sfynx.trigger.onflush_listener:
        class: '%sfynx.trigger.listener.onflush.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: onFlush, connexion: default }

    sfynx.trigger.postflush_listener:
        class: '%sfynx.trigger.listener.postflush.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postFlush, connexion: default }

    sfynx.trigger.preremove_listener:
        class: '%sfynx.trigger.listener.preremove.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: preRemove, connexion: default }

    sfynx.trigger.postremove_listener:
        class: '%sfynx.trigger.listener.postremove.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postRemove, connexion: default }

    sfynx.trigger.prepersist_listener:
        class: '%sfynx.trigger.listener.prepersist.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist, connexion: default }

    sfynx.trigger.postpersist_listener:
        class: '%sfynx.trigger.listener.postpersist.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist, connexion: default }

    sfynx.trigger.preupdate_listener:
        class: '%sfynx.trigger.listener.preupdate.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: preUpdate, connexion: default }

    sfynx.trigger.postupdate_listener:
        class: '%sfynx.trigger.listener.postupdate.class%'
        public: false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postUpdate, connexion: default }